/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_CartesianAngularAccelerationComponent_H_
#define	_CartesianAngularAccelerationComponent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CartesianAngularAccelerationComponentValue.h"
#include "AngularAccelerationConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CartesianAngularAccelerationComponent */
typedef struct CartesianAngularAccelerationComponent {
	CartesianAngularAccelerationComponentValue_t	 value;
	AngularAccelerationConfidence_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CartesianAngularAccelerationComponent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CartesianAngularAccelerationComponent;

#ifdef __cplusplus
}
#endif

#endif	/* _CartesianAngularAccelerationComponent_H_ */
#include "asn_internal.h"
