/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_LongitudinalLanePosition_H_
#define	_LongitudinalLanePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LongitudinalLanePositionValue.h"
#include "LongitudinalLanePositionConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LongitudinalLanePosition */
typedef struct LongitudinalLanePosition {
	LongitudinalLanePositionValue_t	 longitudinalLanePositionValue;
	LongitudinalLanePositionConfidence_t	 longitudinalLanePositionConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LongitudinalLanePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LongitudinalLanePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_LongitudinalLanePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_LongitudinalLanePosition_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LongitudinalLanePosition_H_ */
#include "asn_internal.h"
