/*
 * Generated by asn1c-0.10.0 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "preprocessed_temp/MCM.asn"
 */

#ifndef	_ObjectClassWithConfidence_H_
#define	_ObjectClassWithConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectClass.h"
#include "ConfidenceLevel.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectClassWithConfidence */
typedef struct ObjectClassWithConfidence {
	ObjectClass_t	 objectClass;
	ConfidenceLevel_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectClassWithConfidence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectClassWithConfidence;
extern asn_SEQUENCE_specifics_t asn_SPC_ObjectClassWithConfidence_specs_1;
extern asn_TYPE_member_t asn_MBR_ObjectClassWithConfidence_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectClassWithConfidence_H_ */
#include "asn_internal.h"
