/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Stub header for non-CARLA builds.
 * The real carla-module.h is auto-generated by the carla module's build_lib().
 * This stub satisfies the #include in example files that pull in the carla
 * module header without actually using any carla APIs.
 */

#ifndef CARLA_MODULE_H
#define CARLA_MODULE_H

/* No carla APIs are available in this build. */

#endif // CARLA_MODULE_H
